name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myfastapi:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myfastapi:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/myfastapi:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/myfastapi:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myfastapi:latest
          
  deploy:
      needs: build   # wait for build to finish successfully
      runs-on: ubuntu-latest

      steps:
        - name: Setup SSH agent
          uses: webfactory/ssh-agent@v0.7.0
          with:
            ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

        - name: SSH to EC2 and deploy
          run: |
            ssh -o StrictHostKeyChecking=no admin@${{ secrets.EC2_NAME }} << 'EOF'
              docker rm -f $(docker ps -a -q --filter ancestor=${{ secrets.DOCKERHUB_USERNAME }}/myfastapi:latest) || true
              docker rmi -f ${{ secrets.DOCKERHUB_USERNAME }}/myfastapi:latest || true
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myfastapi:latest
              docker run -d -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/myfastapi:latest
              echo "Deployment completed successfully!"
            EOF